server:
  port: 8081

spring:
  redis:
    database: 0
    host: localhost
    password:
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&connectTimeout=3000&socketTimeout=1000
    username: root
    password: tcy03181030
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5     #池里不会被释放的最多空闲连接数量。设置为0时表示无限制。
    maxActive: 100    #同一时间可以从池分配的最多连接数量。设置为0时表示无限制
    initialSize: 10  #池启动时创建的连接数量
    maxWait: 60000   #在抛出异常之前，池等待连接被回收的最长时间（当没有可用连接时）。设置为-1表示无限等待。
    timeBetweenEvictionRunsMillis: 60000  #毫秒秒检查一次连接池中空闲的连接
    minEvictableIdleTimeMillis: 300000   #连接保持空闲而不被驱逐的最长时间。
    validationQuery: select 'x'    #要求必需是个SELECT类型的SQL语句，至少返回一行，由于它会在所有应用的SQL语句执行之前运行一次，所以原则上应该对数据库服务器带来的压力越小越好，推荐使用“SELECT 1”
    testWhileIdle: true   #如果获取到了不可用的数据库连接，一般由应用处理异常。
    testOnBorrow: false   #表示将连接归还连接池前是否运行validationQuery，true=运行，false=不运行[默认]
    testOnReturn: false   #表示将连接归还连接池前是否运行validationQuery，true=运行，false=不运行[默认]
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码
    cachePrepStmts: true

mybatis:
  type-aliases-package: com.hangyan.mapper
  mapper-locations: classpath:/com/hangyan/mapper/*.xml
  mapperScanPackage: com.hangyan.mapper
  config-location: classpath:/mybatis-config.xml


